unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Window
bind-key v kill-window

set -g base-index 0
set -g renumber-windows off

# Ive made the choice to set window nav to 09876 since 12345 is hard to hit with C-s leader
bind 0 select-window -t 0
bind 9 select-window -t 1
bind 8 select-window -t 2
bind 7 select-window -t 3
bind 6 select-window -t 4

set -g window-status-current-style 'fg=purple'
set -g window-status-current-format ' #I:#W '
set -g window-status-format ' #I:#W '

# Pane
set -g pane-base-index 1

bind-key [ split-window -h
bind-key ] split-window -v
bind-key x kill-pane
unbind '"'
unbind %

set -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g pane-active-border-style 'fg=purple'

# Status bar
set -g status-bg black
set -g status-fg white
set -g status-style 'fg=purple'
